volumes:
  hyrulebnb_db: #déclaration du volume pour la base

services:

  # container de bdd
  database: #nom de service
    container_name: hyrulebnb_db
    image: mariadb:latest
    ports:
      - '3307:3306'
    volumes:
      - hyrulebnb_db:/var/lib/mysql
      - ./db:/root
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyrulebnb
      MYSQL_USER: link
      MYSQL_PASSWORD: hophophopyaaaha

  # container php
  php:
    container_name: hyrulebnb_php
    build:
      context: ./php
    ports:
      - '9001:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: Europe/Paris
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  # server web
  nginx:
    container_name: hyrulebnb_web
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: Europe/Paris
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - php
      - database