<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Connexion - Autodingo.com</title>
</head>
<body>
    <h1>Autodingo</h1>
    <form action="/sign-in" method="post" novalidate>
        <div>
            <label for="input-email">E-Mail :</label>
            <input type="email" name="email" id="input-email">
        </div>
        <div>
            <label for="input-password">Mot de passe :</label>
            <input type="password" name="password" id="input-password">
        </div>
        <div>
            <input type="submit" value="Connexion">
        </div>
    </form>
</body>
</html>